mail.host = sandbox.smtp.mailtrap.io
mail.port = 25
mail.username = 1cfc51e47a9f9f
mail.password = 044f472733dacd
app.mail = info.calivonclothes@gmail.com
app.name = Calivon
app.url = http://localhost:8080/calivon
app.public.url=https://avertedly-unmerciful-moshe.ngrok-free.dev/calivon